#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : doc8
Version  : 0.8.0
Release  : 27
URL      : http://pypi.debian.net/doc8/doc8-0.8.0.tar.gz
Source0  : http://pypi.debian.net/doc8/doc8-0.8.0.tar.gz
Summary  : Style checker for Sphinx (or other) RST documentation
Group    : Development/Tools
License  : Apache-2.0
Requires: doc8-bin
Requires: doc8-python3
Requires: doc8-license
Requires: doc8-python
Requires: chardet
Requires: docutils
Requires: restructuredtext_lint
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: test.patch

%description
Doc8
        ====
        
        Doc8 is an *opinionated* style checker for `rst`_ (with basic support for
        plain text) styles of documentation.
        
        QuickStart
        ==========

%package bin
Summary: bin components for the doc8 package.
Group: Binaries
Requires: doc8-license

%description bin
bin components for the doc8 package.


%package license
Summary: license components for the doc8 package.
Group: Default

%description license
license components for the doc8 package.


%package python
Summary: python components for the doc8 package.
Group: Default
Requires: doc8-python3

%description python
python components for the doc8 package.


%package python3
Summary: python3 components for the doc8 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the doc8 package.


%prep
%setup -q -n doc8-0.8.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532217798
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/doc8
cp LICENSE %{buildroot}/usr/share/doc/doc8/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doc8

%files license
%defattr(-,root,root,-)
/usr/share/doc/doc8/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
